# -*- coding: utf-8 -*-
"""ex2_0903.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19nOJn_59U2TMuCvO0KooNn0tc6RRPIrH
"""

x = 5
y = "John"
print(x)
print(type(x))

def myfunc():
  x = "x"

txt = "Hello, world"
print(len(txt))
print()

for x in txt :
  print(x)
  print("---")
print("***********")

txt = "The best things in life are free!"
print("free" in txt)

txt = "The best things in life are free!"
print(txt[2:5])
print(txt[:5])
print(txt[5:])
print(txt[-5:-2])
print(txt[-5:])
print(txt[:-2])

txt = "The best things in life are free!"
print(txt.upper())

txtup = "THE BEST THINGS IN LIFE ARE FREE!"
print(txt.lower())

txt = " The best things in life are free!    "
print(len(txt))
print(txt)

txt = txt.strip()
print(txt)
print(len(txt))

print(txt.replace("T", "S"))

print(txt.split(" "))

# 클래스 정의
class Person:
  # 클래스 초기화
  def __init__(self, name, age) :
    self.name = name
    self.age = age
  # 메서드 생성
  def greet(self) :
    print("Hello", self.name)
  #출력 메서드
  def display_info(self) :
    print(f"{self.name} {self.age}")

# 객체 생성
p1 = Person("남혜림", 28)
print(p1.name)
print(p1.age)
p1.greet()
p1.display_info()