# -*- coding: utf-8 -*-
"""ex03_0904.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b6pKxmdnppfxzxadFv6KFvn00KdMXY_6
"""

age = 28
txt = f"asd{age}gkj"
print(txt)

txt2 = f"asd{age:.2f}gkj"
print(txt2)

txt = "apple"
x = txt.center(20)
print(x)

y = txt.center(20, "*")
print(y)

txt = "sagjklsag!"
print(txt.isupper())
print(txt.islower())